name: regenerate_readme
on:
  pull_request:
jobs:
  doctests:
    name: "Make Suggestions To Readme"
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6
      - uses: actions/checkout@v1
      - run: julia --color=yes --project=generate/ -e 'import Pkg; Pkg.instantiate()'
      - run: julia --project=generate generate/main.jl
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Regenerate README.md