name: regenerate_readme
on:
  pull_request:
jobs:
  regen:
    name: "Regenerate The README.md"
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: julia --color=yes --project=generate/ -e 'import Pkg; Pkg.instantiate()'
      - run: julia --project=generate generate/main.jl
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Regenerate README.md