name: suggest_readme
on:
  pull_request:
jobs:
  doctests:
    name: "Make Suggestions To Readme"
    runs-on: ubuntu-latest

    
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6
      - uses: actions/checkout@v1
      - run: julia --color=yes --project=generate/ -e 'import Pkg; Pkg.instantiate()'
      - run: julia --project=generate generate/main.jl
      - uses: reviewdog/action-suggester@v1
        if: github.event_name == 'pull_request'
        with:
          tool_name: Suggest
          fail_on_error: true